# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8550-modules/motorola/include
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8550-modules/motorola/include/linux/input/awinic
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8550/drivers/base

ifneq ($(filter m y,$(CONFIG_AW96XX_POWER_SUPPLY_ONLINE)),)
	EXTRA_CFLAGS += -DCONFIG_USE_POWER_SUPPLY_ONLINE
endif

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers

obj-m := awinic_sar.o
awinic_sar-objs := ./comm/aw_sar_comm_interface.o aw_sar.o ./aw9610x/aw9610x.o ./aw9620x/aw9620x.o ./aw9620x/aw_update_fw.o ./aw963xx/aw963xx.o

