# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8550-modules/motorola/include \
		-I$(KERNEL_SRC)/../sm8550-modules/motorola/drivers/power/rt9467_chg_mmi

obj-m += rt9467_charger.o


