# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += \
		-I$(KERNEL_SRC)/../sm8550-modules/motorola/include

obj-m := goodix_brl_mmi.o
goodix_brl_mmi-objs := \
					goodix_brl_i2c.o \
					goodix_brl_spi.o \
					goodix_ts_core.o \
					goodix_brl_hw.o \
					goodix_cfg_bin.o \
					goodix_ts_utils.o \
					goodix_brl_fwupdate.o \
					goodix_ts_inspect.o \
					goodix_ts_tools.o \
					goodix_ts_config.o

ifneq ($(filter m y, $(CONFIG_DRM_PANEL_EVENT_NOTIFICATIONS)),)
	EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_EVENT_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_DRM_PANEL_NOTIFICATIONS)),)
    EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_TOUCHSCREEN_GOODIX_BRL_SPI)),)
    EXTRA_CFLAGS += -DCONFIG_TOUCHSCREEN_GOODIX_BRL_SPI
endif

ifneq ($(filter m y,$(CONFIG_GTP_FOD)),)
    EXTRA_CFLAGS += -DCONFIG_GTP_FOD
    goodix_brl_mmi-objs += goodix_ts_gesture_fod.o
else
    goodix_brl_mmi-objs += goodix_ts_gesture.o
endif

ifneq ($(filter m y,$(CONFIG_GTP_LIMIT_USE_SUPPLIER)),)
    EXTRA_CFLAGS += -DCONFIG_GTP_LIMIT_USE_SUPPLIER
endif

ifneq ($(filter m y,$(CONFIG_GTP_ENABLE_PM_QOS)),)
    EXTRA_CFLAGS += -DCONFIG_GTP_ENABLE_PM_QOS
endif

ifneq ($(filter m y,$(CONFIG_GOODIX_ESD_ENABLE)),)
    EXTRA_CFLAGS += -DCONFIG_GOODIX_ESD_ENABLE
endif

ifneq ($(filter m y,$(CONFIG_TARGET_BUILD_FACROTY)),)
    EXTRA_CFLAGS += -DGTP_SAVE_IN_CSV
endif

ifneq ($(filter m y,$(CONFIG_GTP_LAST_TIME)),)
    EXTRA_CFLAGS += -DCONFIG_GTP_LAST_TIME
endif

ifneq ($(filter m y,$(CONFIG_GTP_DDA_STYLUS)),)
    EXTRA_CFLAGS += -DCONFIG_GTP_DDA_STYLUS
    goodix_brl_mmi-objs += goodix_ts_dda.o
endif

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
    EXTRA_CFLAGS += -DCONFIG_INPUT_TOUCHSCREEN_MMI
    goodix_brl_mmi-objs += goodix_ts_mmi.o
endif

ifneq ($(filter m y, $(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL)),)
	EXTRA_CFLAGS += -DCONFIG_BOARD_USES_DOUBLE_TAP_CTRL
endif

ifneq ($(findstring _factory,$(TARGET_PRODUCT)),)
USE_TARGET_PRODUCT := $(strip $(subst _factory,, $(TARGET_PRODUCT)))
else
USE_TARGET_PRODUCT := $(TARGET_PRODUCT)
endif

ifneq ($(findstring oneli, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_ONELI
else ifneq ($(findstring hiphi, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_HIPHI
else ifneq ($(findstring hiphic, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_HIPHIC
else ifneq ($(findstring li, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_LI
else ifneq ($(findstring eqs, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_EQS
else ifneq ($(findstring tundra, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_TUNDRA
else ifneq ($(findstring miami, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_MIAMI
else ifneq ($(findstring rtwo, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_RTWO
else ifneq ($(findstring bronco, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_BRONCO
else ifneq ($(findstring felix, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DCONFIG_GTP_DISP_MODE
else ifneq ($(findstring zeekr, $(USE_TARGET_PRODUCT)), )
        EXTRA_CFLAGS += -DPRODUCT_ZEEKR
endif

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../touchscreen_mmi/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_info/Module.symvers
